### ISSUE TITLE
an error is reported when getting metadata

### ISSUE THREAD

**Issue by monoplasty** [JinmiaoChenLab/DISCOtoolkit_py#4]
Hi,

Thank you for your amazing tool!

When I used discotoolkit to get the sample's matadata, I found an error.

my code
```python
import discotoolkit as dt

filter = dt.Filter(
    platform=["10x3'", "10x5'"]
)
metadata = dt.filter_disco_metadata(filter)
print(metadata.sample_metadata.shape)
```

the error
```
INFO:root:Retrieving metadata from DISCO database
INFO:root:Filtering sample
INFO:root:Retrieving cell type information of each sample from DISCO database
Traceback (most recent call last):
  File "D:\Code\PycharmProjects\bio_data_download\disco_down.py", line 45, in <module>
    metadata = down_10x()
  File "D:\Code\PycharmProjects\bio_data_download\disco_down.py", line 8, in down_10x
    metadata = dt.filter_disco_metadata(filter)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\discotoolkit\GetMetadata.py", line 228, in filter_disco_metadata
    metadata["cell_number"] = list(sample_cell_count.loc[list(metadata["sampleId"])]["x"]) # assigning to the metadata
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1301, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1239, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexing.py", line 1432, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexes\base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "D:\Develop\miniconda3\envs\py39\lib\site-packages\pandas\core\indexes\base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['GSM5741306'] not in index"

```

two weeks ago it was working fine. I don't know where is the problem, my version is discotoolkit 1.1.2. thank you very much!

**Comment by uddamvathanak** [comment]
Hi there,

Thank you so much for using discotoolkitpy!

I have addressed the issue that you mentioned in the version of discotoolkit.

please upgrade the discotoolkit using this command below:

`python -m pip install -U discotoolkit`

which would update to 1.1.3 version.

Please, let me know if there are any other error and cheer! 😄
