### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Chengyuanyue** [JinmiaoChenLab/DISCOtoolkit_py#7]
Thanks for your excellent work! DISCO helped me a lot with collecting data!
However, there was something wrong when I downloaded data. It reported problem as follow:
TimeoutError: [Errno 110] Connection timed out
Could you please help me solve it? 
I will appreciate it if you reply to my letter! Thanks for your time!

**Comment by lmw123** [comment]
Hi,

Thanks for your feedback! Could you share your codes with us for debugging? @uddamvathanak Rom our main developer of DISCOtoolkit_py will help with the issue. Thanks

Best regards,
Mengwei

**Comment by Chengyuanyue** [comment]
Thanks for your reply. My code is 

`import discotoolkit as dt
import os
import scanpy as sc
import anndata as ad
import re
import matplotlib.pyplot as plt

# adding ignore warning to clean the code
import warnings

# Ignore all warnings
warnings.filterwarnings('ignore')

# filtering the sample based on the metadata
filter = dt.Filter(
    sample_id = None,
    project_id = None,
    tissue = "lung",
    platform = ["10x3'"],
    sample_type = ["control"],
    cell_type = "LYVE1 macrophage",
    cell_type_confidence = "high",
    include_cell_type_children = True,
    min_cell_per_sample = 300
)

# apply the filter of interest
metadata = dt.filter_disco_metadata(filter)

# download data to the local directory
dir_path = "data"
download_log = dt.download_disco_data(metadata, output_dir = dir_path)`


and it reported
`raceback (most recent call last):
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 980, in send
    self.connect()
  File "D:\software\miniconda\conda\envs\bio\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\software\miniconda\conda\envs\bio\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\software\miniconda\conda\envs\bio\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\software\miniconda\conda\envs\bio\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\2_softwaredata\python\DISCO\get_data.py", line 28, in <module>
    metadata = dt.filter_disco_metadata(filter)
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\discotoolkit\GetMetadata.py", line 211, in filter_disco_metadata
    metadata = get_disco_metadata()  # get metadata
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\discotoolkit\GetMetadata.py", line 103, in get_disco_metadata
    metadata = pd.read_csv(
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\common.py", line 384, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "D:\software\miniconda\conda\envs\bio\lib\site-packages\pandas\io\common.py", line 289, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\software\miniconda\conda\envs\bio\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>`

**Comment by uddamvathanak** [comment]
Hi Chengyuanyue, I have tested the code on my side and it work well. May I get your library version for the request.

Moreover, is the installation is in a fresh environment?

Thanks,

Rom Uddamvathanak

**Comment by Chengyuanyue** [comment]
Hey, sorry to bother you again. I followed the installation guide from github and installed discotoool_py in a fresh environment again. At the first time, I searched 13 samples and it worked well. However, for my purpose, I want to download all of the data. When I tried to do that, it didn't work again. Is there some solution to have a better connection when downloading the large scale data? Thanks for your time!

**Comment by lmw123** [comment]
> However, for my purpose, I want to download all of the data. When I tried to do that, it didn't work again. Is there some solution to have a better connection when downloading the large scale data?

Hi Yuanyue,

We are creating a single file that will contain all the data from the current version of DISCO, allowing for bulk download. This file will be available next week, and you will be able to download it as soon as it's ready.

Best regards,
Mengwei

**Comment by lmw123** [comment]
@Chengyuanyue 

Hi Yuanyue,

We’ve updated our database to support batch downloads of all data in DISCO. You can now access the latest files directly from the download page (https://www.immunesinglecell.org/download). Feel free to explore, and let us know if you encounter any issues.

Best regards,
Mengwei

**Comment by Chengyuanyue** [comment]
Thanks for your excellent work again! Plus, it's so kind to package all the data and allow users to download it publicly! However, there was something wrong when I tried to open the URL of the data files. I tried all the URLs, both h5 and rds format files. Could you please check the problem? Thanks for your time!
![image](https://github.com/user-attachments/assets/178c02a1-b2dc-409a-a3a7-1177a85fd416)

**Comment by lmw123** [comment]
@Chengyuanyue Hi Yuanyue,

Thanks for your reply! I looked into the issues and found they're due to high traffic—the data is quite large, and currently, over 10 users are downloading it simultaneously 😂. To help, I’m also uploading a backup to Zenodo, which should be available soon. I appreciate your patience, and we'll work on making the download process smoother.

![Screenshot 2024-11-14 at 10 16 22](https://github.com/user-attachments/assets/a85c384d-e4a8-4a79-b34c-f65a884d2c2b)

Thank you!

**Comment by lmw123** [comment]
@Chengyuanyue

Hi Yuanyue,

If you're in a hurry, feel free to add me on WeChat at funny_lmw, and I can share a private download link with you.
